include:
  - ./common.yaml
  - ./proxy.yaml
  - ./storage-sites.yaml

services:
  cifs:
    image: ${NEXOEDGE_CIFS_IMAGE_NAME}:${TAG}
    ports:
      - "445:445"
    volumes:
      - type: bind
        source: ${NEXOEDGE_DATA_DIR}/cifs-metadata
        target: /usr/local/samba/var
      - type: bind
        source: ${NEXOEDGE_DATA_DIR}/cifs-share-metadata
        target: /smb/nexoedge
    networks:
      - nexoedge
    depends_on:
      - metastore
      - statsdb
      - proxy
      - site-1
      - site-2
      - site-3
      - site-4
      - reporter
      - portal-backend
      - portal-frontend

